name: Terraform Deploy to Prod


#on:
#  workflow_dispatch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # <-- THIS enables GitHub to mint the OIDC token

    defaults:
      run:
        working-directory: ./terraform/envs/test

    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ secrets.GCP_REGION }}
      TF_VAR_zone: ${{ secrets.GCP_ZONE }}
      TF_LOG: DEBUG

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP (OIDC -> WIF)
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          #credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify VM access (list VMs)
        run: |
          gcloud compute instances list \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --filter="name=${{ secrets.GCP_VM_NAME }}"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Show Plan
        run: terraform show -no-color tfplan
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
